version: '3.9'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=devinove
      - POSTGRES_PASSWORD=devinove
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
